name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
        
    - name: Create deployment directory
      run: |
        # Create deployment directory
        mkdir -p public
        
        # Copy root index.html
        cp index.html public/
        
        # Copy static app to imageprompt2 subdirectory
        mkdir -p public/imageprompt2
        cp static-app/index.html public/imageprompt2/
        
        # List what we're deploying
        echo "=== Deployment directory structure ==="
        find public -type f
        echo "=== End of file list ==="
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        force_orphan: true