name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        npm install --legacy-peer-deps
        
    - name: Build project
      run: |
        cd apps/nextjs
        npm install --legacy-peer-deps
        echo "Trying basic build first..."
        npm run build-basic || echo "Basic build failed, trying simple build..."
        npm run build-simple || echo "Simple build failed, trying full build..."
        npm run build || echo "All builds failed, will use fallback"
        
    - name: List build output
      run: |
        echo "Checking build output..."
        ls -la apps/nextjs/out/ || echo "No out directory found"
        
    - name: Prepare deployment directory
      run: |
        mkdir -p deploy
        # Copy root index.html
        cp index.html deploy/
        # Copy Next.js build if it exists
        if [ -d apps/nextjs/out ]; then
          echo "Copying Next.js build output..."
          cp -r apps/nextjs/out/* deploy/ 2>/dev/null || echo "No Next.js output to copy"
        else
          echo "No Next.js output directory found, using fallback"
          cp test-index.html deploy/index.html
        fi
        # List final deployment directory
        echo "Final deployment directory contents:"
        ls -la deploy/
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/master'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./deploy