name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        npm install --legacy-peer-deps
        
    - name: Build project
      run: |
        cd apps/nextjs
        npm install --legacy-peer-deps
        npm run build-simple || npm run build
        
    - name: List build output
      run: |
        echo "Checking build output..."
        ls -la apps/nextjs/out/ || echo "No out directory found"
        
    - name: Create fallback index if needed
      run: |
        if [ ! -f apps/nextjs/out/index.html ]; then
          echo "Creating fallback index.html"
          mkdir -p apps/nextjs/out
          cp test-index.html apps/nextjs/out/index.html
        fi
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/master'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./apps/nextjs/out